services:
  firestore:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    command: [gcloud, emulators, firestore, start, --host-port=0.0.0.0:8080, --project=calendar-sync-test, --quiet]
    ports: ["127.0.0.1:8686:8080"]
